GET http://localhost:3000 HTTP/1.1
###
GET https://localhost:3000 HTTP/1.1
###
GET https://localhost:3000/api/test HTTP/1.1
###
POST https://localhost:3000/api/fruits HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwidXNlcmlkIjoiNjViODBjMzEzZjZiNzAyNjg5ZjExNzUwIiwiaWF0IjoxNzA2NjE0NTYzLCJleHAiOjE3MDY2MTgxNjN9.CyHJ5L8b1dCRjdczBdyr9HaUVFgNTI_paFPkOSJYk4g

{
    "id": "56",
    "name": "tomato"
}
###

GET https://localhost:3000/api/fruits HTTP/1.1
###
DELETE https://localhost:3000/api/fruits/65b68d839b90e458929a3490 HTTP/1.1
###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "password": "admin"
}
###

POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "password": "admin"
}
###
